# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Spacewar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Spacewar)

$(call add-radio-file-sha1-checked,radio/abl.img,3942a661c0b6e585c46823723f609dc0457fe6c5)
$(call add-radio-file-sha1-checked,radio/aop.img,45d47e5f2d5f910809a68de16692e561df728927)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,8cdde249020138abe0707a0fa2b8d15ef40ed6bd)
$(call add-radio-file-sha1-checked,radio/cpucp.img,256a60281c5417fe5b71d9469a225e8e71cc1574)
$(call add-radio-file-sha1-checked,radio/devcfg.img,12db5058ccc4cf68a2da92cadf1eb8f0acec896d)
$(call add-radio-file-sha1-checked,radio/dsp.img,afe65f6671c989fc2ee30c52c6ed9cb797f1d5cc)
$(call add-radio-file-sha1-checked,radio/featenabler.img,049cd37d5b695ddbb334b178a93f7645cdbb9c09)
$(call add-radio-file-sha1-checked,radio/hyp.img,960e7a6b62c7173c99ea930bdb81fa3ee5d5ca1b)
$(call add-radio-file-sha1-checked,radio/imagefv.img,9adfaed0393703871c14b86679a7a64855860b8b)
$(call add-radio-file-sha1-checked,radio/keymaster.img,ed3f38cfbb2bb8f9450bd6932b0c12820ec59342)
$(call add-radio-file-sha1-checked,radio/modem.img,c61894b798039addae0ddbfd27797c4d473df417)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,e349b8fffc7dc6d89ce60c5b50c2fb6fb42e953f)
$(call add-radio-file-sha1-checked,radio/qupfw.img,b4a6d5912b327143709b4f338a3330e1f1616e1e)
$(call add-radio-file-sha1-checked,radio/shrm.img,3eced9a8dfa116265a386f78bc567689dcefd21a)
$(call add-radio-file-sha1-checked,radio/tz.img,76fe774aa1e7b0e5aabac7221b5e296cc48d0877)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,d94d0f0c8cad77c6f5a5c531e7eb574f22989b49)
$(call add-radio-file-sha1-checked,radio/xbl.img,e59185ce7ad058fcd151cfc0c544dbc753712b36)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,9f47e7e7514e12debc8c67475add9e85b1b1839f)

endif
