# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Spacewar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Spacewar)

$(call add-radio-file-sha1-checked,radio/abl.img,6078b0e7615a80ba3963b151dacba54be88650bf)
$(call add-radio-file-sha1-checked,radio/aop.img,dbcf4d2a94bec7c7a90b0d7c0492d245171b7637)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,2c40472667f958807921910aeaefa411239108f5)
$(call add-radio-file-sha1-checked,radio/cpucp.img,546de012dd6b781eacb6682f922d7ff34495e712)
$(call add-radio-file-sha1-checked,radio/devcfg.img,4443495cdf16a6a90dfaefba38a772b0c26a6e30)
$(call add-radio-file-sha1-checked,radio/dsp.img,afe65f6671c989fc2ee30c52c6ed9cb797f1d5cc)
$(call add-radio-file-sha1-checked,radio/featenabler.img,ea1692cc361f631dadbe84456dfba652514f1a9c)
$(call add-radio-file-sha1-checked,radio/hyp.img,212c068e75a1feaa0221d335ec5c2d134d783f9e)
$(call add-radio-file-sha1-checked,radio/imagefv.img,85de6c16e5ae6422aedf1abe080e8f90a643b7db)
$(call add-radio-file-sha1-checked,radio/keymaster.img,d975ec443355b125036ffa8f4402d8f688d823d7)
$(call add-radio-file-sha1-checked,radio/modem.img,7923c986c3a20bfa358613e971ad643c950ce1a3)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,2351a838d1f9a60315d1e5b34427f2cde5cd79a0)
$(call add-radio-file-sha1-checked,radio/qupfw.img,c9cc4db35c35ac6bc96fd20235382a90d4de28ec)
$(call add-radio-file-sha1-checked,radio/shrm.img,caab486112c6e132be4f6490b5b9d68f61a255b5)
$(call add-radio-file-sha1-checked,radio/tz.img,b3e1216128153f981dde037d569fd3d581de951c)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,c5ed070b1daddf589b0fb3871b8a6705c72b0714)
$(call add-radio-file-sha1-checked,radio/xbl.img,67539c875f6186d09a2f0550e8309be11e3ef901)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,110cd09db4ed64e227409f6b1fe0d242c98be759)

endif
