# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Spacewar/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    aop \
    bluetooth \
    cpucp \
    devcfg \
    dsp \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    modem \
    multiimgoem \
    qupfw \
    shrm \
    tz \
    uefisecapp \
    xbl \
    xbl_config
